# Generated by Django 5.1.2 on 2024-11-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
